Add volume configuration
claranet/terraform-azurerm-aci pull request #1
Opened 2022-10-08 23:01 UTC by oleksiimorozenko

This patch adds container volume configuration

2022-10-10 13:07 UTC, Shr3ps commented
Thanks for your contribution.

Can we rebase this to the next version of the module to use Terraform 1.3? or do you need this with older terraform/azurerm version?

2022-10-17 12:49 UTC, rossifumax requested changes

2022-10-17 12:49 UTC, rossifumax commented on variables.tf
> +    volume = maps(object({
```suggestion
    volume = map(object({
```

2022-10-17 12:49 UTC, rossifumax commented on variables.tf
> +    volume = maps(object({
Can you format this file with `terraform fmt` please ?

2022-10-17 12:49 UTC, rossifumax commented on r-aci.tf
> +
```suggestion
```
This is not needed

2022-10-19 20:34 UTC, oleksiimorozenko commented on variables.tf
> +    volume = maps(object({
It _is_ formatted with `fmt`

2022-10-19 20:42 UTC, oleksiimorozenko commented
> Can we rebase this to the next version of the module to use Terraform 1.3? or do you need this with older terraform/azurerm version?

I used Terraform v1.3.0 when patching/testing and applying my configuration without any problem so I think yes, v1.3 looks good, but
```│ Warning: Deprecated attribute
│
│   on .terraform/modules/diagnostics/locals.tf line 8, in locals:
│    8:     try(data.azurerm_monitor_diagnostic_categories.main[0].logs, [])
│
│ The attribute "logs" is deprecated. Refer to the provider documentation for details.
│
│ (and one more similar warning elsewhere)
```
is telling us that there is submodule which needs to be upgraded as Azure 4.x provider comes into scene

2022-10-21 15:06 UTC, Shr3ps approved these changes

2022-10-21 15:06 UTC, merged

2022-10-21 15:21 UTC, Shr3ps commented
Released in v7.1.0

Thanks